
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver被弃用
    type: com.alibaba.druid.pool.DruidDataSource #使用阿里的连接池
server:
  port: 8888

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

# xml 跟bean  所在位置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.domain

#thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

logging: #配置sql控制台打印
  level:
    com.example.demo.mapper : debug
   #pattern:
    #file: "my.log.%d{yyyy-MM-dd}.log"
     # console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    #path: "./logs"
     #file:
      #max-history: 30
      #max-size: 10MB


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#jpa:
  #hibernate:
    #ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
  #show-sql: true


quartz:
  #相关属性配置
  properties:
    org:
      quartz:
        scheduler:
          instanceName: clusteredScheduler
          instanceId: AUTO
        #jobStore:
          #class: org.quartz.impl.jdbcjobstore.JobStoreTX
          #driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          #tablePrefix: QRTZ_
          #isClustered: true
          #clusterCheckinInterval: 10000
          #useProperties: false
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 10
          threadPriority: 5
          threadsInheritContextClassLoaderOfInitializingThread: true
  #数据库方式
  #job-store-type: jdbc
    #初始化表结构
    #jdbc:
  #initialize-schema: never
